name: CI

on:
  push:
    branches:
    - "**"


# see:
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4

      - name: test
        run: |
            rye sync
            rye test


  publish:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --prune --tags

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4

    - name: Build dist
      run: |
        rye build --verbose

    - name: publish to pypi
      run: |
        rye publish --token ${{ secrets.PYPI_TOKEN }} --yes --verbose

    - name: push tag
      run: |
        gh release create $(rye version)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
